/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author Esaú
 */
public class Arboles_Binarios extends javax.swing.JFrame {

    /**
     * Creates new form Arboles_Binarios
     */
    public Arboles_Binarios() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        panel_Round_JWC2 = new swing.Panel_Round_JWC();
        jLabel2 = new javax.swing.JLabel();
        btn_Round_JWC2 = new swing.Btn_Round_JWC();
        btn_Round_JWC3 = new swing.Btn_Round_JWC();
        btn_Round_JWC4 = new swing.Btn_Round_JWC();
        btn_Round_JWC5 = new swing.Btn_Round_JWC();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_Round_JWC1 = new swing.Btn_Round_JWC();
        btn_Round_JWC6 = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_Round_JWC1.setBackground(new java.awt.Color(255, 255, 255));
        panel_Round_JWC1.setEsqInferiorDerecha(50);
        panel_Round_JWC1.setEsqInferiorIzquierda(50);
        panel_Round_JWC1.setEsqSuperiorDerecha(50);
        panel_Round_JWC1.setEsqSuperiorIzquierda(50);

        panel_Round_JWC2.setBackground(new java.awt.Color(51, 51, 51));
        panel_Round_JWC2.setEsqInferiorIzquierda(50);
        panel_Round_JWC2.setEsqSuperiorIzquierda(50);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Opciones:");

        btn_Round_JWC2.setBackground(new java.awt.Color(0, 204, 204));
        btn_Round_JWC2.setText("Cargar Archivo a BD");
        btn_Round_JWC2.setArco_esquina(20);
        btn_Round_JWC2.setColor_H_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC2.setColor_Hover(new java.awt.Color(0, 153, 153));
        btn_Round_JWC2.setColor_N_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC2.setColor_Normal(new java.awt.Color(0, 204, 204));

        btn_Round_JWC3.setBackground(new java.awt.Color(0, 204, 204));
        btn_Round_JWC3.setText("Generar Árbol");
        btn_Round_JWC3.setArco_esquina(20);
        btn_Round_JWC3.setColor_H_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC3.setColor_Hover(new java.awt.Color(0, 153, 153));
        btn_Round_JWC3.setColor_N_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC3.setColor_Normal(new java.awt.Color(0, 204, 204));

        btn_Round_JWC4.setBackground(new java.awt.Color(0, 204, 204));
        btn_Round_JWC4.setText("Imprimir Árbol");
        btn_Round_JWC4.setArco_esquina(20);
        btn_Round_JWC4.setColor_H_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC4.setColor_Hover(new java.awt.Color(0, 153, 153));
        btn_Round_JWC4.setColor_N_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC4.setColor_Normal(new java.awt.Color(0, 204, 204));

        btn_Round_JWC5.setBackground(new java.awt.Color(0, 204, 204));
        btn_Round_JWC5.setText("Limpiar base de datos");
        btn_Round_JWC5.setArco_esquina(20);
        btn_Round_JWC5.setColor_H_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC5.setColor_Hover(new java.awt.Color(0, 153, 153));
        btn_Round_JWC5.setColor_N_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC5.setColor_Normal(new java.awt.Color(0, 204, 204));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("1.");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("2.");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("3.");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("4.");

        javax.swing.GroupLayout panel_Round_JWC2Layout = new javax.swing.GroupLayout(panel_Round_JWC2);
        panel_Round_JWC2.setLayout(panel_Round_JWC2Layout);
        panel_Round_JWC2Layout.setHorizontalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Round_JWC5, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(btn_Round_JWC4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btn_Round_JWC3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btn_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(45, 45, 45))
        );
        panel_Round_JWC2Layout.setVerticalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btn_Round_JWC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btn_Round_JWC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btn_Round_JWC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Arboles Binarios");

        btn_Round_JWC1.setBackground(new java.awt.Color(153, 0, 0));
        btn_Round_JWC1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Round_JWC1.setText("X");
        btn_Round_JWC1.setArco_esquina(30);
        btn_Round_JWC1.setColor_Hover(new java.awt.Color(51, 0, 0));
        btn_Round_JWC1.setColor_Normal(new java.awt.Color(153, 0, 0));
        btn_Round_JWC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Round_JWC1ActionPerformed(evt);
            }
        });

        btn_Round_JWC6.setBackground(new java.awt.Color(0, 204, 204));
        btn_Round_JWC6.setText("Menú Principal");
        btn_Round_JWC6.setArco_esquina(20);
        btn_Round_JWC6.setColor_H_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC6.setColor_Hover(new java.awt.Color(0, 153, 153));
        btn_Round_JWC6.setColor_N_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC6.setColor_Normal(new java.awt.Color(0, 204, 204));
        btn_Round_JWC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Round_JWC6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_JWC1Layout = new javax.swing.GroupLayout(panel_Round_JWC1);
        panel_Round_JWC1.setLayout(panel_Round_JWC1Layout);
        panel_Round_JWC1Layout.setHorizontalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btn_Round_JWC6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Round_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_Round_JWC1Layout.setVerticalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Round_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Round_JWC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Round_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Round_JWC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Round_JWC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Round_JWC1ActionPerformed
        // TODO add your handling code here:
        Cerrar vCerrar =new Cerrar();
        
    }//GEN-LAST:event_btn_Round_JWC1ActionPerformed

    private void btn_Round_JWC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Round_JWC6ActionPerformed
        // TODO add your handling code here:
        MenúPrincipal vMenu =new MenúPrincipal();
        dispose();
    }//GEN-LAST:event_btn_Round_JWC6ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Btn_Round_JWC btn_Round_JWC1;
    private swing.Btn_Round_JWC btn_Round_JWC2;
    private swing.Btn_Round_JWC btn_Round_JWC3;
    private swing.Btn_Round_JWC btn_Round_JWC4;
    private swing.Btn_Round_JWC btn_Round_JWC5;
    private swing.Btn_Round_JWC btn_Round_JWC6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    private swing.Panel_Round_JWC panel_Round_JWC2;
    // End of variables declaration//GEN-END:variables
}
