/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author Esaú
 */
public class MenúPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenúPrincipal
     */
    public MenúPrincipal() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        panel_Round_JWC2 = new swing.Panel_Round_JWC();
        btn_ArbolBin = new swing.Btn_Round_JWC();
        lblopciones = new javax.swing.JLabel();
        lblUno = new javax.swing.JLabel();
        lblDos = new javax.swing.JLabel();
        lblTres = new javax.swing.JLabel();
        btn_Round_JWC2 = new swing.Btn_Round_JWC();
        btn_Round_JWC3 = new swing.Btn_Round_JWC();
        lblMenú = new javax.swing.JLabel();
        btn_Cerrar = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_Round_JWC1.setBackground(new java.awt.Color(255, 255, 255));
        panel_Round_JWC1.setEsqInferiorDerecha(50);
        panel_Round_JWC1.setEsqInferiorIzquierda(50);
        panel_Round_JWC1.setEsqSuperiorDerecha(50);
        panel_Round_JWC1.setEsqSuperiorIzquierda(50);

        panel_Round_JWC2.setBackground(new java.awt.Color(51, 51, 51));
        panel_Round_JWC2.setEsqInferiorIzquierda(50);
        panel_Round_JWC2.setEsqSuperiorIzquierda(50);

        btn_ArbolBin.setBackground(new java.awt.Color(51, 255, 255));
        btn_ArbolBin.setText("Arboles Binarios");
        btn_ArbolBin.setArco_esquina(20);
        btn_ArbolBin.setColor_H_text(new java.awt.Color(0, 0, 0));
        btn_ArbolBin.setColor_Hover(new java.awt.Color(0, 153, 153));
        btn_ArbolBin.setColor_N_text(new java.awt.Color(0, 0, 0));
        btn_ArbolBin.setColor_Normal(new java.awt.Color(0, 204, 204));
        btn_ArbolBin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ArbolBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ArbolBinActionPerformed(evt);
            }
        });

        lblopciones.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblopciones.setForeground(new java.awt.Color(204, 204, 204));
        lblopciones.setText("Opciones:");

        lblUno.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblUno.setForeground(new java.awt.Color(204, 204, 204));
        lblUno.setText("1.");

        lblDos.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblDos.setForeground(new java.awt.Color(204, 204, 204));
        lblDos.setText("2.");

        lblTres.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblTres.setForeground(new java.awt.Color(204, 204, 204));
        lblTres.setText("3.");

        btn_Round_JWC2.setBackground(new java.awt.Color(0, 204, 204));
        btn_Round_JWC2.setText("..........");
        btn_Round_JWC2.setArco_esquina(20);
        btn_Round_JWC2.setColor_H_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC2.setColor_Hover(new java.awt.Color(0, 153, 153));
        btn_Round_JWC2.setColor_N_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC2.setColor_Normal(new java.awt.Color(0, 204, 204));

        btn_Round_JWC3.setBackground(new java.awt.Color(0, 204, 204));
        btn_Round_JWC3.setText("..........");
        btn_Round_JWC3.setArco_esquina(20);
        btn_Round_JWC3.setColor_H_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC3.setColor_Hover(new java.awt.Color(0, 153, 153));
        btn_Round_JWC3.setColor_N_text(new java.awt.Color(0, 0, 0));
        btn_Round_JWC3.setColor_Normal(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout panel_Round_JWC2Layout = new javax.swing.GroupLayout(panel_Round_JWC2);
        panel_Round_JWC2.setLayout(panel_Round_JWC2Layout);
        panel_Round_JWC2Layout.setHorizontalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC2Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                        .addComponent(lblUno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ArbolBin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                            .addComponent(lblTres)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_Round_JWC3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC2Layout.createSequentialGroup()
                            .addComponent(lblDos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblopciones)
                .addGap(36, 36, 36))
        );
        panel_Round_JWC2Layout.setVerticalGroup(
            panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblopciones)
                .addGap(18, 18, 18)
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ArbolBin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Round_JWC2Layout.createSequentialGroup()
                        .addComponent(btn_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(panel_Round_JWC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTres)
                            .addComponent(btn_Round_JWC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblDos))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        lblMenú.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblMenú.setForeground(new java.awt.Color(0, 0, 0));
        lblMenú.setText("Menú Principal");

        btn_Cerrar.setBackground(new java.awt.Color(102, 0, 0));
        btn_Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cerrar.setText("X");
        btn_Cerrar.setArco_esquina(30);
        btn_Cerrar.setColor_Hover(new java.awt.Color(51, 0, 0));
        btn_Cerrar.setColor_Normal(new java.awt.Color(102, 0, 0));
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_JWC1Layout = new javax.swing.GroupLayout(panel_Round_JWC1);
        panel_Round_JWC1.setLayout(panel_Round_JWC1Layout);
        panel_Round_JWC1Layout.setHorizontalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblMenú)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panel_Round_JWC1Layout.setVerticalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMenú)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Round_JWC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Round_JWC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        // TODO add your handling code here:
        Cerrar vCerrar = new Cerrar();
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void btn_ArbolBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ArbolBinActionPerformed
        // TODO add your handling code here:
        Arboles_Binarios vArboles = new Arboles_Binarios();
        dispose();
    }//GEN-LAST:event_btn_ArbolBinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenúPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenúPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Btn_Round_JWC btn_ArbolBin;
    private swing.Btn_Round_JWC btn_Cerrar;
    private swing.Btn_Round_JWC btn_Round_JWC2;
    private swing.Btn_Round_JWC btn_Round_JWC3;
    private javax.swing.JLabel lblDos;
    private javax.swing.JLabel lblMenú;
    private javax.swing.JLabel lblTres;
    private javax.swing.JLabel lblUno;
    private javax.swing.JLabel lblopciones;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    private swing.Panel_Round_JWC panel_Round_JWC2;
    // End of variables declaration//GEN-END:variables
}
